capture = wlr
encoder = nvenc
adapter_name = /dev/dri/renderD128
output_name = HEADLESS-1
audio_sink = steam-stream
file_apps = /config/sunshine/apps.json
credentials_file = /config/sunshine/sunshine_state.json
log_path = /config/sunshine/sunshine.log
pkey = /config/sunshine/credentials/cakey.pem
cert = /config/sunshine/credentials/cacert.pem
system_tray = disabled
origin_web_ui_allowed = lan
upnp = disabled
